export const COMMANDS = {
    LOGGER: {
        GET_LOGS: 'GET_LOGS'
    },
    CONTENT: {
        CREATE: 'CREATE_CONTENT',
        GET_BY_SLUG: 'GET_BY_SLUG',
        GET_BODY_BY_SLUG: 'GET_BODY_BY_SLUG',
        GET_BY_ID: 'GET_BY_ID',
        GET_BODY_BY_ID: 'GET_BODY_C_BY_ID',
        GET: 'GET_CONTENT',
        UPDATE: 'UPDATE_CONTENT',
        PUBLISH: 'PUBLISH',
        GET_TAGS: 'GET_TAGS',
        GET_SERIES: 'GET_SERIES',
        GET_ALL_SERIES_CONTENT_COUNT: 'GET_ALL_SERIES_CONTENT_COUNT'
    },
    BLOG: {
        CREATE: 'CREATE_BLOG',
        GET_ENTRY_BY_SLUG: 'GET_ENTRY_BY_SLUG',
        CREATE_ENTRY: 'CREATE_ENTRY',
        UPDATE_ENTRY: 'UPDATE_ENTRY',
        CREATE_CATEGORY: 'CREATE_CATEGORY',
        GET_CATEGORIES: 'GET_CATEGORIES',
        RENAME_CATEGORY: 'RENAME_CATEGORY',
        GET_ENTRIES: 'GET_ENTRIES',
        PUBLISH: 'PUBLISH'
    },
    NOTIFICATION: {
        GET_LOGGED_USER_SUBSCRIPTIONS: 'GET_LOGGED_USER_SUBSCRIPTIONS',
        SUBSCRIBE_TO_PUBLISHER: 'SUBSCRIBE_TO_PUBLISHER',
        UNSUBSCRIBE_FROM_PUBLISHER: 'UNSUBSCRIBE_FROM_PUBLISHER',
        SUBSCRIBE_TO_TAG: 'SUBSCRIBE_TO_TAG',
        UNSUBSCRIBE_FROM_TAG: 'UNSUBSCRIBE_FROM_TAG',
        SEND_CONTENT_PUBLISHED_NOTIFICATIONS: 'SEND_CONTENT_PUBLISHED_NOTIFICATIONS'
    },
    USER: {
        GET_BY_ID: "GET_BY_ID",
        GET_BY_EMAIL: "GET_BY_EMAIL"
    }
}